const $ = (s) => document.querySelector(s);
const $$ = (s) => document.querySelectorAll(s);
const drawer = $('#alertDrawer');
const backdrop = $('#drawerBackdrop');
const toast = $('#toast');
const overviewMarkup = $('#pageContent').innerHTML;
let toastTimer;
const pageMeta = {
  overview:{label:'Overview',kicker:'LIVE SECURITY OVERVIEW',title:'Good morning, Alex.',desc:'One place to understand who can access what — and why.'},
  people:{label:'Users',kicker:'DIRECTORY',title:'People',desc:'Manage identities, roles, and access across your workspace.'},
  groups:{label:'Groups',kicker:'DIRECTORY',title:'Groups',desc:'Organize people into reusable access boundaries.'},
  guests:{label:'Guests',kicker:'DIRECTORY',title:'Guests',desc:'Review external identities and their time-bound access.'},
  roles:{label:'Roles',kicker:'ACCESS CONTROL',title:'Roles',desc:'Define capability bundles and keep privilege boundaries clear.'},
  permissions:{label:'Permissions',kicker:'ACCESS CONTROL',title:'Permission matrix',desc:'See effective access across roles, resources, and actions.'},
  apps:{label:'App access',kicker:'ACCESS CONTROL',title:'App access',desc:'Control which applications are available to each identity group.'},
  auth:{label:'Authentication',kicker:'AUTHENTICATION',title:'Authentication',desc:'Set the rules that protect every sign-in.'},
  alerts:{label:'Alerts',kicker:'SECURITY OPERATIONS',title:'Alerts',desc:'Investigate unusual activity and resolve risk with confidence.'},
  sessions:{label:'Sessions',kicker:'SECURITY OPERATIONS',title:'Sessions',desc:'See where identities are active and revoke risk quickly.'},
  audit:{label:'Audit log',kicker:'EVIDENCE',title:'Audit log',desc:'A searchable record of every important access decision.'}
};
function showToast(message){ $('#toastText').textContent=message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove('show'),2600); }
function openDrawer(){drawer.classList.add('open');backdrop.classList.add('open');document.body.style.overflow='hidden';}
function closeDrawer(){drawer.classList.remove('open');backdrop.classList.remove('open');document.body.style.overflow='';}
function icon(name){return `<span class="ui-icon ui-icon-${name}" aria-hidden="true"></span>`;}
const people = [
  ['Maria Santos','maria.santos@northstar.dev','MS','Engineering','Member','Active','12 min ago'],
  ['Jordan Lee','jordan.lee@orbit.io','JL','Product','Guest','Pending invite','42 min ago'],
  ['Alex Kim','alex.kim@northstar.dev','AK','Operations','Org admin','Active','1 hour ago'],
  ['Priya Nair','priya.nair@northstar.dev','PN','Data','Member','Active','3 hours ago'],
  ['Theo Martin','theo.martin@northstar.dev','TM','Engineering','Member','Suspended','Yesterday']
];
const data = {
  people:{columns:['IDENTITY','TEAM','ROLE','STATUS','LAST ACTIVE'],rows:people.map(p=>`<tr><td><div class="entity"><span class="entity-avatar">${p[2]}</span><div><strong>${p[0]}</strong><small>${p[1]}</small></div></div></td><td>${p[3]}</td><td><span class="role-pill">${p[4]}</span></td><td><span class="state ${p[5].toLowerCase().replaceAll(' ','-')}">${p[5]}</span></td><td class="muted-cell">${p[6]}</td><td><button class="row-menu">···</button></td></tr>`)},
  groups:{columns:['GROUP','MEMBERS','ACCESS SCOPE','OWNER','STATUS'],rows:[['Engineering','24','12 resources','Alex Kim','Active'],['Product designers','18','6 resources','Priya Nair','Active'],['Finance','11','4 resources','Theo Martin','Active'],['Contractors','32','3 resources','Operations','Review due']].map(r=>`<tr><td><div class="entity"><span class="entity-icon">${icon('group')}</span><div><strong>${r[0]}</strong><small>Managed group</small></div></div></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td><span class="state ${r[4]==='Active'?'active':'review-due'}">${r[4]}</span></td><td><button class="row-menu">···</button></td></tr>`)},
  guests:{columns:['IDENTITY','COMPANY','SPONSOR','ACCESS EXPIRES','STATUS'],rows:[['Jordan Lee','Orbit Studio','Alex Kim','Sep 30, 2026','Pending invite'],['Dana Wu','Figma','Priya Nair','Oct 12, 2026','Active'],['Samir Patel','Northwind','Alex Kim','Sep 18, 2026','Review due'],['Elena Rossi','Freelance','Operations','Expired','Suspended']].map(r=>`<tr><td><div class="entity"><span class="entity-avatar guest">${r[0].split(' ').map(x=>x[0]).join('')}</span><div><strong>${r[0]}</strong><small>External identity</small></div></div></td><td>${r[1]}</td><td>${r[2]}</td><td class="muted-cell">${r[3]}</td><td><span class="state ${r[4].toLowerCase().replaceAll(' ','-')}">${r[4]}</span></td><td><button class="row-menu">···</button></td></tr>`)},
  roles:{columns:['ROLE','MEMBERS','PRIVILEGE','SCOPE','LAST CHANGED'],rows:[['Engineering','24','Standard','12 resources','8 min ago'],['Security admin','3','Privileged','All security','Yesterday'],['App admin','8','Elevated','18 applications','Sep 14'],['Auditor','5','Read only','All resources','Sep 10'],['Guest','18','Limited','Assigned only','Sep 02']].map(r=>`<tr><td><div class="entity"><span class="entity-icon role">${icon('role')}</span><div><strong>${r[0]}</strong><small>Role definition</small></div></div></td><td>${r[1]}</td><td><span class="role-pill ${r[2].toLowerCase().replaceAll(' ','-')}">${r[2]}</span></td><td>${r[3]}</td><td class="muted-cell">${r[4]}</td><td><button class="row-menu">···</button></td></tr>`)},
  apps:{columns:['APPLICATION','OWNERS','ASSIGNED','ACCESS POLICY','STATUS'],rows:[['Linear','Product','86 people','SSO + MFA','Healthy'],['Figma','Design','42 people','SSO required','Healthy'],['AWS Console','Platform','18 people','Step-up MFA','Review due'],['Salesforce','Revenue','31 people','SSO + device trust','Healthy'],['Notion','All teams','144 people','SSO','Healthy']].map(r=>`<tr><td><div class="entity"><span class="entity-icon app">${icon('app')}</span><div><strong>${r[0]}</strong><small>Connected application</small></div></div></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td><span class="state ${r[4].toLowerCase().replaceAll(' ','-')}">${r[4]}</span></td><td><button class="row-menu">···</button></td></tr>`)},
  alerts:{columns:['ALERT','PRINCIPAL','RISK','DETECTED','STATUS'],rows:[['Suspicious login','Maria Santos','High','12 min ago','Open'],['MFA bypass request','CI bot','Medium','2 hours ago','Open'],['Policy conflict','Engineering role','Low','Yesterday','Review due'],['Guest access expired','Elena Rossi','Low','Sep 14','Resolved']].map(r=>`<tr><td><div class="entity"><span class="entity-icon alert">${icon('alert')}</span><div><strong>${r[0]}</strong><small>Security signal</small></div></div></td><td>${r[1]}</td><td><span class="risk ${r[2].toLowerCase()}">${r[2]}</span></td><td class="muted-cell">${r[3]}</td><td><span class="state ${r[4].toLowerCase().replaceAll(' ','-')}">${r[4]}</span></td><td><button class="row-menu">···</button></td></tr>`)},
  sessions:{columns:['IDENTITY','DEVICE','LOCATION','LAST SEEN','STATUS'],rows:people.slice(0,4).map((p,i)=>`<tr><td><div class="entity"><span class="entity-avatar">${p[2]}</span><div><strong>${p[0]}</strong><small>${p[1]}</small></div></div></td><td>${['Chrome · macOS','Chrome · Windows','Safari · macOS','CLI token'][i]}</td><td>${['London, UK','São Paulo, BR','Singapore, SG','Dublin, IE'][i]}</td><td class="muted-cell">${p[6]}</td><td><span class="state ${i===1?'risk-state':'active'}">${i===1?'Needs review':'Active'}</span></td><td><button class="btn tiny danger-outline">Revoke</button></td></tr>`)},
  audit:{columns:['EVENT','ACTOR','TARGET','TIME','RESULT'],rows:[['Role updated','Alex Kim','Engineering · permissions','8 min ago','Success'],['Session revoked','Alex Kim','Maria Santos · Chrome','12 min ago','Success'],['Guest invited','Alex Kim','jordan.lee@orbit.io','42 min ago','Success'],['Policy exception requested','CI bot','MFA bypass','2 hours ago','Pending'],['Role assignment removed','Priya Nair','Contractors','Yesterday','Success']].map(r=>`<tr><td><div class="entity"><span class="entity-icon audit">${icon('audit')}</span><div><strong>${r[0]}</strong><small>Immutable event</small></div></div></td><td>${r[1]}</td><td>${r[2]}</td><td class="muted-cell">${r[3]}</td><td><span class="state ${r[4].toLowerCase()}">${r[4]}</span></td><td><button class="row-menu">···</button></td></tr>`)}
};
function tablePage(view){const meta=pageMeta[view];const d=data[view];return `<div class="page-heading inner-heading"><div><div class="eyebrow">${meta.kicker} <span class="mono">•</span> SEP 16, 2026</div><h1>${meta.title}</h1><p>${meta.desc}</p></div><div class="heading-actions"><button class="btn secondary" data-action="export">↓ <span>Export</span></button><button class="btn primary" data-action="create">+ <span>${view==='roles'?'New role':view==='apps'?'Connect app':view==='alerts'?'Investigate':'Add '+meta.label.toLowerCase().replace('users','user')}</span></button></div></div><div class="subnav-strip"><span class="subnav-active">${meta.label}</span><span>${view==='audit'?'All events':view==='alerts'?'Open alerts':'All '+meta.label.toLowerCase()}</span><span>Needs review</span><span>Recently changed</span></div><div class="page-metrics"><div><small>Total</small><strong>${view==='people'?'248':view==='groups'?'32':view==='guests'?'18':view==='roles'?'12':view==='apps'?'36':view==='alerts'?'03':view==='sessions'?'41':'1,284'}</strong></div><div><small>Needs review</small><strong class="metric-warn">${view==='people'?'5':view==='guests'?'3':view==='alerts'?'3':view==='sessions'?'2':'4'}</strong></div><div><small>Last 30 days</small><strong class="metric-green">96.8%</strong></div></div><div class="section-row page-section-row"><div><div class="section-kicker">${view==='audit'?'EVIDENCE STREAM':'WORKSPACE DIRECTORY'}</div><h2>${meta.label} list</h2><p class="section-sub">Filter, inspect, and take action without losing your current context.</p></div><button class="text-btn" data-action="saved">Saved views →</button></div><div class="list-card"><div class="list-toolbar"><div class="list-search">⌕<input class="list-filter" placeholder="Search ${meta.label.toLowerCase()}..." /></div><button class="btn secondary" data-action="filter">≡ <span>Filters</span><b class="filter-badge">2</b></button><button class="btn secondary" data-action="columns">▥ <span>Columns</span></button></div><div class="active-filters"><span>Active</span><span>All teams</span><span class="clear-filters">Clear all ×</span></div><div class="table-wrap"><table class="permission-table enterprise-table"><thead><tr>${d.columns.map(c=>`<th>${c} <span>↕</span></th>`).join('')}<th></th></tr></thead><tbody>${d.rows.join('')}</tbody></table></div><div class="matrix-footer"><span>Showing <b>${d.rows.length}</b> of ${view==='audit'?'1,284':view==='people'?'248':'36'} records</span><button class="pagination active">1</button><button class="pagination">2</button><button class="pagination">3</button><span>···</span><button class="pagination">8</button><button class="next-page">Next →</button></div></div>`}
function specialPage(view){const meta=pageMeta[view];if(view==='permissions')return `<div class="page-heading inner-heading"><div><div class="eyebrow">ACCESS CONTROL <span class="mono">•</span> EFFECTIVE ACCESS</div><h1>Permission matrix</h1><p>Understand role, resource, action, inheritance, and effective access in one view.</p></div><div class="heading-actions"><button class="btn secondary" data-action="export">↓ <span>Export report</span></button><button class="btn primary" data-action="create">+ <span>New role</span></button></div></div><div class="matrix-explainer"><div><span class="explainer-mark">↗</span><div><strong>Engineering access is 98.2% policy-derived.</strong><span>Review the 4 exceptions before your next access review.</span></div></div><button class="text-btn">Review exceptions →</button></div>${document.querySelector('.matrix-card').outerHTML}`;if(view==='auth')return `<div class="page-heading inner-heading"><div><div class="eyebrow">AUTHENTICATION <span class="mono">•</span> 8 POLICIES</div><h1>Authentication</h1><p>Set clear, enforceable sign-in rules for every identity cohort.</p></div><div class="heading-actions"><button class="btn secondary" data-action="test">Test policy</button><button class="btn primary" data-action="create">+ <span>New policy</span></button></div></div><div class="policy-summary"><div class="policy-score"><span>96</span><small>%</small></div><div><strong>Policy compliance</strong><span>24 of 25 controls are active</span></div><div class="policy-bar"><span></span></div><button class="text-btn">View report →</button></div><div class="policy-list"><div class="policy-row"><div class="policy-symbol">◎</div><div><strong>Baseline sign-in</strong><span>All members · Password + MFA</span></div><span class="state active">Enforced</span><button class="row-menu">···</button></div><div class="policy-row"><div class="policy-symbol">◉</div><div><strong>Privileged access</strong><span>Admins · Phishing-resistant MFA</span></div><span class="state active">Enforced</span><button class="row-menu">···</button></div><div class="policy-row"><div class="policy-symbol">◌</div><div><strong>Guest access</strong><span>Guests · SSO + device trust</span></div><span class="state review-due">Review due</span><button class="row-menu">···</button></div></div>`;return tablePage(view)}
function showView(view){const target=$('#pageContent');if(view==='overview')target.innerHTML=overviewMarkup;else target.innerHTML=specialPage(view);$('#breadcrumbCurrent').textContent=pageMeta[view].label;window.scrollTo({top:0,behavior:'smooth'});bindViewEvents();}
function bindViewEvents(){const search=$('.list-filter');if(search)search.addEventListener('input',e=>{$$('.enterprise-table tbody tr').forEach(row=>row.style.display=row.textContent.toLowerCase().includes(e.target.value.toLowerCase())?'':'none');});$$('[data-action]').forEach(b=>b.addEventListener('click',()=>showToast(({export:'Report prepared for download',create:'Draft created — ready for review',filter:'Showing 2 active filters',columns:'Column preferences opened',saved:'Saved views opened',test:'Policy test mode enabled'}[b.dataset.action])||'Action completed')));$$('.permission').forEach(btn=>btn.addEventListener('click',()=>{if(btn.classList.contains('deny')){btn.className='permission allow';btn.innerHTML='✓<span>Explicit</span>';showToast('Permission changed to explicit allow')}else if(btn.classList.contains('allow')){btn.className='permission deny';btn.innerHTML='—<span>Denied</span>';showToast('Permission denied for this role')}else showToast('Inherited access comes from Platform baseline')}));$$('.row-menu').forEach(btn=>btn.addEventListener('click',()=>showToast('Resource actions opened')));}
$('#inspectBtn').addEventListener('click',openDrawer);$('#closeDrawer').addEventListener('click',closeDrawer);backdrop.addEventListener('click',closeDrawer);$('#closeAlert').addEventListener('click',()=>{$('#alertBanner').style.display='none';showToast('Alert archived from overview')});$('#revokeBtn').addEventListener('click',()=>{closeDrawer();showToast('Session revoked and added to audit log')});$('#dismissBtn').addEventListener('click',()=>{closeDrawer();$('#alertBanner').style.display='none';showToast('Alert marked as reviewed')});$('#exportBtn').addEventListener('click',()=>showToast('Security report prepared for download'));$('#addBtn').addEventListener('click',()=>showToast('Invite flow opened'));$('#newRoleBtn').addEventListener('click',()=>showToast('New role draft created'));$('#filterBtn').addEventListener('click',()=>showToast('Showing 2 active filters: resource + state'));$('#viewMatrix').addEventListener('click',()=>document.querySelector('.matrix-card').scrollIntoView({behavior:'smooth',block:'center'}));$$('.toggle').forEach(btn=>btn.addEventListener('click',()=>{$$('.toggle').forEach(b=>b.classList.remove('active'));btn.classList.add('active');showToast(btn.textContent.trim()+' view selected')}));$('#matrixSearch').addEventListener('input',(e)=>{const q=e.target.value.toLowerCase();$$('#permissionRows tr').forEach(row=>row.style.display=row.dataset.resource.includes(q)?'':'none')});
$$('.nav-item').forEach(item=>item.addEventListener('click',()=>{$$('.nav-item').forEach(i=>i.classList.remove('active'));item.classList.add('active');$('#sidebar').classList.remove('open');showView(item.dataset.view)}));$('#mobileMenu').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));document.addEventListener('keydown',(e)=>{if(e.key==='Escape')closeDrawer();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();const input=$('.list-filter')||$('#matrixSearch');if(input)input.focus()}});bindViewEvents();
